import type { Transaction } from '@/types/transaction';
import type { DashboardSummary, AnalyticsData, Anomaly } from '@/types/analytics';
import type { User, UserSettings } from '@/types/user';

export const MOCK_USER: User = {
  id: 'usr_001',
  name: 'Kaelen Vance',
  email: 'kvance@neon.grid',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASxpqbsFVvL7iUpdmk_Co9vhIwQt8fepwg1BWyg-CbLvopyPW84Ca9KdJM1kmOgeip3SHpGhQAQ3hb-uAuTQQ26art9YgjF2T-t1tLf2SSOqoKvzWSCKKIvOdrKbS_RSVE_QPjZq-qi81kOv05mJj7GKvcdZIOcFUvezDgdQBGtNf-poPpJYMaW6mAgDystG2Cc_rSGJwDOU5mM-QVoiiqbuKg2VzqkiLRwxkJZfDGD7Vwn3ToAhTRmuhOGBu2MJdBK9VHmf4c1xIc',
  plan: 'pro',
  clearanceLevel: 4,
  currency: 'USD',
  nodeVersion: 'v2.4.9-Stable',
};

export const MOCK_USER_SETTINGS: UserSettings = {
  currency: 'USD',
  theme: 'dark',
  notifications: {
    budgetThresholds: true,
    dailySummary: true,
    systemUpdates: false,
  },
  twoFactorEnabled: true,
};

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  totalBalance: 24500.0,
  monthlyIncome: 8200.0,
  monthlyExpenses: 3450.0,
  balanceChangePercent: 12.4,
  savingsGoalProgress: 88,
};

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_001',
    title: 'Neural-Link Upgrade',
    description: 'Cyber-Hardware Store',
    category: 'Cyber-Hardware',
    amount: 2400.0,
    type: 'expense',
    date: '2077-10-24',
    paymentMethod: 'Crypto-Node',
    icon: 'cpu',
  },
  {
    id: 'txn_002',
    title: 'Neo-Tokyo Salary',
    description: 'Monthly earnings deposit',
    category: 'Earnings',
    amount: 8500.0,
    type: 'income',
    date: '2077-10-22',
    paymentMethod: 'Direct Deposit',
    icon: 'trending_up',
  },
  {
    id: 'txn_003',
    title: 'Syn-Noodle Bar',
    description: 'Nutrition',
    category: 'Nutrition',
    amount: 45.5,
    type: 'expense',
    date: '2077-10-21',
    paymentMethod: 'Direct Debit',
    icon: 'restaurant',
  },
  {
    id: 'txn_004',
    title: 'Maglev Commute',
    description: 'Monthly transport pass',
    category: 'Transport',
    amount: 120.0,
    type: 'expense',
    date: '2077-10-20',
    paymentMethod: 'Direct Debit',
    icon: 'train',
  },
  {
    id: 'txn_005',
    title: 'Freelance Data Bounty',
    description: 'Design Sprint #04',
    category: 'Earnings',
    amount: 1200.0,
    type: 'income',
    date: '2077-10-18',
    paymentMethod: 'Crypto-Node',
    icon: 'payments',
  },
  {
    id: 'txn_006',
    title: 'Orbital Stream Sub',
    description: 'Monthly entertainment subscription',
    category: 'Entertainment',
    amount: 29.99,
    type: 'expense',
    date: '2077-10-17',
    paymentMethod: 'Direct Debit',
    icon: 'live_tv',
  },
  {
    id: 'txn_007',
    title: 'Residential Core Rent',
    description: 'Monthly apartment payment',
    category: 'Housing',
    amount: 1200.0,
    type: 'expense',
    date: '2077-10-15',
    paymentMethod: 'Direct Debit',
    icon: 'home',
  },
  {
    id: 'txn_008',
    title: 'Iron Works Node',
    description: 'Gym membership',
    category: 'Healthcare',
    amount: 85.0,
    type: 'expense',
    date: '2077-10-14',
    paymentMethod: 'Direct Debit',
    icon: 'fitness_center',
  },
  {
    id: 'txn_009',
    title: 'Neo-Tokyo Cafe',
    description: 'Morning coffee ritual',
    category: 'Nutrition',
    amount: 5.4,
    type: 'expense',
    date: '2077-10-13',
    paymentMethod: 'Direct Debit',
    icon: 'coffee',
  },
  {
    id: 'txn_010',
    title: 'Cloud Server Node',
    description: 'Data hosting services',
    category: 'Subscriptions',
    amount: 49.0,
    type: 'expense',
    date: '2077-10-12',
    paymentMethod: 'Crypto-Node',
    icon: 'cloud',
  },
  {
    id: 'txn_011',
    title: 'Freelance Design Sprint',
    description: 'Sprint #03 final payment',
    category: 'Earnings',
    amount: 2450.0,
    type: 'income',
    date: '2077-10-10',
    paymentMethod: 'Crypto-Node',
    icon: 'payments',
  },
  {
    id: 'txn_012',
    title: 'Neon Market Groceries',
    description: 'Weekly food supplies',
    category: 'Food',
    amount: 180.0,
    type: 'expense',
    date: '2077-10-08',
    paymentMethod: 'Direct Debit',
    icon: 'shopping_cart',
  },
];

export const MOCK_RECENT_TRANSACTIONS = MOCK_TRANSACTIONS.slice(0, 4);

export const MOCK_ANALYTICS: AnalyticsData = {
  avgDailySpending: 142.5,
  avgDailyChangePercent: 4.2,
  highestCategory: 'Housing',
  highestCategoryPercent: 32,
  topExpenditures: [
    { label: 'Rent & Utilities', amount: 2400, color: '#ff2d78' },
    { label: 'Dining & Food', amount: 842, color: '#00ffcc' },
    { label: 'Entertainment', amount: 520, color: '#ffe04a' },
    { label: 'Transport', amount: 310, color: '#5a5068' },
  ],
  monthlyTrend: [
    { label: 'JAN', amount: 3200 },
    { label: 'FEB', amount: 2800 },
    { label: 'MAR', amount: 3600 },
    { label: 'APR', amount: 3100 },
    { label: 'MAY', amount: 4200 },
    { label: 'JUN', amount: 3450 },
    { label: 'JUL', amount: 2900 },
    { label: 'AUG', amount: 3800 },
    { label: 'SEP', amount: 4100 },
    { label: 'OCT', amount: 3450 },
    { label: 'NOV', amount: 3200 },
    { label: 'DEC', amount: 3600 },
  ],
  categoryBreakdown: [
    { category: 'Housing', amount: 1680, percentage: 32, color: '#ff2d78' },
    { category: 'Food', amount: 1312.5, percentage: 25, color: '#00ffcc' },
    { category: 'Leisure', amount: 787.5, percentage: 15, color: '#ffe04a' },
    { category: 'Transport', amount: 525, percentage: 10, color: '#5a5068' },
    { category: 'Other', amount: 945, percentage: 18, color: '#302840' },
  ],
  efficiencyScore: 92.4,
  efficiencyChangePercent: 12,
};

export const MOCK_ANOMALIES: Anomaly[] = [
  {
    id: 'anm_001',
    type: 'warning',
    title: 'Unusual Subscription',
    description: 'Cloud Service - $29.99 (New)',
  },
  {
    id: 'anm_002',
    type: 'positive',
    title: 'Transport Savings',
    description: '-$45 compared to average',
  },
  {
    id: 'anm_003',
    type: 'info',
    title: 'No other anomalies detected.',
    description: 'All systems nominal',
  },
];
